"""
Export API Routes — generate markdown and JSON exports.
GET /api/export/{run_id}/json
GET /api/export/{run_id}/markdown
"""
import json
import logging
from decimal import Decimal
from fastapi import APIRouter, HTTPException
from fastapi.responses import Response
from backend.services.pipeline_service import get_run

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/export", tags=["Export"])


class DecimalEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, Decimal):
            return float(obj)
        return super().default(obj)


def _get_null_pct(stats, row_count=0):
    if not stats:
        return 0.0
    if stats.get("null_percentage") is not None:
        return stats["null_percentage"]
    if row_count and row_count > 0 and "null_count" in stats:
        return round((stats["null_count"] / row_count) * 100, 2)
    return 0.0


def _get_unique_pct(stats, row_count=0):
    if not stats:
        return 0.0
    if stats.get("unique_percentage") is not None:
        return stats["unique_percentage"]
    if row_count and row_count > 0 and "unique_count" in stats:
        return round((stats["unique_count"] / row_count) * 100, 2)
    return 0.0


def generate_markdown(schema_data: dict) -> str:
    """Generate a complete markdown data dictionary from schema data."""
    total_tables = len(schema_data)
    total_cols = sum(len(t.get("columns", {})) for t in schema_data.values())
    total_rows = sum(t.get("row_count", 0) for t in schema_data.values())
    avg_health = (
        sum(t.get("health_score", 100) for t in schema_data.values()) / total_tables
        if total_tables
        else 0
    )
    pii_cols = [
        f"{t}.{c}"
        for t, tm in schema_data.items()
        for c, cm in tm.get("columns", {}).items()
        if "PII" in (cm.get("tags") or [])
    ]

    md = "# Data Dictionary — SchemaDoc AI\n\n"
    md += "*Generated by SchemaDoc AI Pipeline*\n\n"
    md += "## Database Overview\n\n"
    md += f"| Metric | Value |\n|--------|-------|\n"
    md += f"| Tables | {total_tables} |\n"
    md += f"| Total Columns | {total_cols} |\n"
    md += f"| Total Rows | {total_rows:,} |\n"
    md += f"| Avg Health Score | {avg_health:.1f}/100 |\n"
    md += f"| PII Columns Detected | {len(pii_cols)} |\n\n"
    md += "---\n\n"

    for table, meta in schema_data.items():
        row_count = meta.get("row_count", 0)
        hs = meta.get("health_score", 100)
        md += f"## Table: `{table}`\n"
        md += f"**Rows:** {row_count:,} | **Health Score:** {hs}/100\n\n"
        fks = meta.get("foreign_keys", [])
        if fks:
            md += "**Foreign Keys:** "
            md += ", ".join(
                [
                    f"`{fk['column']}` → `{fk['referred_table']}.{fk['referred_column']}`"
                    for fk in fks
                ]
            )
            md += "\n\n"
        md += "| Column | Type | Null % | Unique % | Description | Tags |\n"
        md += "|--------|------|--------|----------|-------------|------|\n"
        for col_name, col_data in meta.get("columns", {}).items():
            stats = col_data.get("stats") or {}
            null_pct = _get_null_pct(stats, row_count)
            uniq_pct = _get_unique_pct(stats, row_count)
            tags_str = ", ".join(col_data.get("tags", []))
            desc = (col_data.get("description") or "—").replace("\n", " ").replace("|", "\\|")
            md += f"| `{col_name}` | `{col_data.get('original_type', 'N/A')}` | {null_pct}% | {uniq_pct}% | {desc} | {tags_str} |\n"
        md += "\n---\n\n"

    md += "*End of Data Dictionary*\n"
    return md


@router.get("/{run_id}/json")
async def export_json(run_id: str):
    """Export enriched schema as JSON."""
    run = get_run(run_id)
    if not run:
        raise HTTPException(status_code=404, detail=f"Run '{run_id}' not found")
    schema = run.get("schema_enriched")
    if not schema:
        raise HTTPException(status_code=400, detail="No schema data available")

    content = json.dumps(schema, indent=2, cls=DecimalEncoder)
    return Response(
        content=content,
        media_type="application/json",
        headers={"Content-Disposition": f"attachment; filename=schema_{run_id}.json"},
    )


@router.get("/{run_id}/markdown")
async def export_markdown(run_id: str):
    """Export enriched schema as Markdown data dictionary."""
    run = get_run(run_id)
    if not run:
        raise HTTPException(status_code=404, detail=f"Run '{run_id}' not found")
    schema = run.get("schema_enriched")
    if not schema:
        raise HTTPException(status_code=400, detail="No schema data available")

    md_content = generate_markdown(schema)
    return Response(
        content=md_content,
        media_type="text/markdown",
        headers={
            "Content-Disposition": f"attachment; filename=data_dictionary_{run_id}.md"
        },
    )
